include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_single_quotes: true
    #
    prefer_relative_imports: true
    prefer_const_constructors: true
    sort_child_properties_last: true
    prefer_final_fields: true
    avoid_print: true